services:
  - type: web
    name: airtel-inventory
    runtime: docker
    repo: https://github.com/Asifiwe13/airtel-inventory
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render

databases:
  - name: airtel-db
    databaseName: airtel_inventory
    user: airtel_user
    plan: free
